# Inventario Ansible — TFM Defensa Activa
# Actualizar ansible_user con el usuario real de cada máquina

[honeypot]
10.0.2.3 ansible_user=osboxes ansible_ssh_private_key_file=~/.ssh/id_tfm ansible_python_interpreter=/usr/bin/python3

[manager]
10.0.2.5 ansible_connection=local ansible_python_interpreter=/usr/bin/python3

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
